import type { Country } from "@keurflow/types";

// Reference data used to seed the `countries` table (Phase 4) and as static
// fallback for labels/flags in the UI. At runtime the `countries` table in
// Postgres is the source of truth — new countries are added there, not here,
// so activating a new market never requires a redeploy.
//
// currencyCode here is only ever the *country's* reference currency, not a
// constraint on what currency a project/funding/expense can use (see
// currencies.ts / CURRENCIES) and not a constraint on billing: an
// organization is billed in XOF/XAF only if its country is in that CFA zone
// (isCfaCurrency), every other country — including the ones below whose
// currencyCode isn't in the CURRENCIES list at all — bills in EUR by
// default (getBillingCurrency's fallback). So a non-African country only
// needs a *plausible* reference currency, not one KeurFlow actually
// transacts in; EUR is used for that reference on every country below where
// USD/GBP/CAD (already-supported transaction currencies) don't apply more
// specifically.
export const COUNTRIES: readonly Omit<Country, "id">[] = [
  // Afrique — marché principal (spec §4, §24)
  { code: "SN", name: "Sénégal", currencyCode: "XOF", active: true },
  { code: "CI", name: "Côte d'Ivoire", currencyCode: "XOF", active: true },
  { code: "ML", name: "Mali", currencyCode: "XOF", active: true },
  { code: "GN", name: "Guinée", currencyCode: "GNF", active: true },
  { code: "MR", name: "Mauritanie", currencyCode: "MRU", active: true },
  { code: "BF", name: "Burkina Faso", currencyCode: "XOF", active: true },
  { code: "NE", name: "Niger", currencyCode: "XOF", active: true },
  { code: "BJ", name: "Bénin", currencyCode: "XOF", active: true },
  { code: "TG", name: "Togo", currencyCode: "XOF", active: true },
  { code: "CM", name: "Cameroun", currencyCode: "XAF", active: true },
  { code: "GA", name: "Gabon", currencyCode: "XAF", active: true },
  { code: "CG", name: "Congo", currencyCode: "XAF", active: true },
  { code: "CD", name: "RDC", currencyCode: "CDF", active: true },
  { code: "CV", name: "Cap-Vert", currencyCode: "CVE", active: true },

  // Reste de l'Afrique
  { code: "DZ", name: "Algérie", currencyCode: "EUR", active: true },
  { code: "AO", name: "Angola", currencyCode: "EUR", active: true },
  { code: "BW", name: "Botswana", currencyCode: "EUR", active: true },
  { code: "BI", name: "Burundi", currencyCode: "EUR", active: true },
  { code: "CF", name: "République centrafricaine", currencyCode: "XAF", active: true },
  { code: "KM", name: "Comores", currencyCode: "EUR", active: true },
  { code: "DJ", name: "Djibouti", currencyCode: "EUR", active: true },
  { code: "EG", name: "Égypte", currencyCode: "EUR", active: true },
  { code: "GQ", name: "Guinée équatoriale", currencyCode: "XAF", active: true },
  { code: "ER", name: "Érythrée", currencyCode: "EUR", active: true },
  { code: "SZ", name: "Eswatini", currencyCode: "EUR", active: true },
  { code: "ET", name: "Éthiopie", currencyCode: "EUR", active: true },
  { code: "GM", name: "Gambie", currencyCode: "EUR", active: true },
  { code: "GH", name: "Ghana", currencyCode: "EUR", active: true },
  { code: "GW", name: "Guinée-Bissau", currencyCode: "XOF", active: true },
  { code: "KE", name: "Kenya", currencyCode: "EUR", active: true },
  { code: "LS", name: "Lesotho", currencyCode: "EUR", active: true },
  { code: "LR", name: "Liberia", currencyCode: "EUR", active: true },
  { code: "LY", name: "Libye", currencyCode: "EUR", active: true },
  { code: "MG", name: "Madagascar", currencyCode: "EUR", active: true },
  { code: "MW", name: "Malawi", currencyCode: "EUR", active: true },
  { code: "MA", name: "Maroc", currencyCode: "EUR", active: true },
  { code: "MU", name: "Maurice", currencyCode: "EUR", active: true },
  { code: "MZ", name: "Mozambique", currencyCode: "EUR", active: true },
  { code: "NA", name: "Namibie", currencyCode: "EUR", active: true },
  { code: "NG", name: "Nigeria", currencyCode: "EUR", active: true },
  { code: "RW", name: "Rwanda", currencyCode: "EUR", active: true },
  { code: "ST", name: "Sao Tomé-et-Principe", currencyCode: "EUR", active: true },
  { code: "SC", name: "Seychelles", currencyCode: "EUR", active: true },
  { code: "SL", name: "Sierra Leone", currencyCode: "EUR", active: true },
  { code: "SO", name: "Somalie", currencyCode: "EUR", active: true },
  { code: "ZA", name: "Afrique du Sud", currencyCode: "EUR", active: true },
  { code: "SS", name: "Soudan du Sud", currencyCode: "EUR", active: true },
  { code: "SD", name: "Soudan", currencyCode: "EUR", active: true },
  { code: "TZ", name: "Tanzanie", currencyCode: "EUR", active: true },
  { code: "TD", name: "Tchad", currencyCode: "XAF", active: true },
  { code: "TN", name: "Tunisie", currencyCode: "EUR", active: true },
  { code: "UG", name: "Ouganda", currencyCode: "EUR", active: true },
  { code: "ZM", name: "Zambie", currencyCode: "EUR", active: true },
  { code: "ZW", name: "Zimbabwe", currencyCode: "EUR", active: true },

  // Europe
  { code: "AL", name: "Albanie", currencyCode: "EUR", active: true },
  { code: "AD", name: "Andorre", currencyCode: "EUR", active: true },
  { code: "AT", name: "Autriche", currencyCode: "EUR", active: true },
  { code: "BY", name: "Biélorussie", currencyCode: "EUR", active: true },
  { code: "BE", name: "Belgique", currencyCode: "EUR", active: true },
  { code: "BA", name: "Bosnie-Herzégovine", currencyCode: "EUR", active: true },
  { code: "BG", name: "Bulgarie", currencyCode: "EUR", active: true },
  { code: "HR", name: "Croatie", currencyCode: "EUR", active: true },
  { code: "CY", name: "Chypre", currencyCode: "EUR", active: true },
  { code: "CZ", name: "République tchèque", currencyCode: "EUR", active: true },
  { code: "DK", name: "Danemark", currencyCode: "EUR", active: true },
  { code: "EE", name: "Estonie", currencyCode: "EUR", active: true },
  { code: "FI", name: "Finlande", currencyCode: "EUR", active: true },
  { code: "FR", name: "France", currencyCode: "EUR", active: true },
  { code: "DE", name: "Allemagne", currencyCode: "EUR", active: true },
  { code: "GR", name: "Grèce", currencyCode: "EUR", active: true },
  { code: "HU", name: "Hongrie", currencyCode: "EUR", active: true },
  { code: "IS", name: "Islande", currencyCode: "EUR", active: true },
  { code: "IE", name: "Irlande", currencyCode: "EUR", active: true },
  { code: "IT", name: "Italie", currencyCode: "EUR", active: true },
  { code: "XK", name: "Kosovo", currencyCode: "EUR", active: true },
  { code: "LV", name: "Lettonie", currencyCode: "EUR", active: true },
  { code: "LI", name: "Liechtenstein", currencyCode: "EUR", active: true },
  { code: "LT", name: "Lituanie", currencyCode: "EUR", active: true },
  { code: "LU", name: "Luxembourg", currencyCode: "EUR", active: true },
  { code: "MT", name: "Malte", currencyCode: "EUR", active: true },
  { code: "MD", name: "Moldavie", currencyCode: "EUR", active: true },
  { code: "MC", name: "Monaco", currencyCode: "EUR", active: true },
  { code: "ME", name: "Monténégro", currencyCode: "EUR", active: true },
  { code: "NL", name: "Pays-Bas", currencyCode: "EUR", active: true },
  { code: "MK", name: "Macédoine du Nord", currencyCode: "EUR", active: true },
  { code: "NO", name: "Norvège", currencyCode: "EUR", active: true },
  { code: "PL", name: "Pologne", currencyCode: "EUR", active: true },
  { code: "PT", name: "Portugal", currencyCode: "EUR", active: true },
  { code: "RO", name: "Roumanie", currencyCode: "EUR", active: true },
  { code: "RU", name: "Russie", currencyCode: "EUR", active: true },
  { code: "SM", name: "Saint-Marin", currencyCode: "EUR", active: true },
  { code: "RS", name: "Serbie", currencyCode: "EUR", active: true },
  { code: "SK", name: "Slovaquie", currencyCode: "EUR", active: true },
  { code: "SI", name: "Slovénie", currencyCode: "EUR", active: true },
  { code: "ES", name: "Espagne", currencyCode: "EUR", active: true },
  { code: "SE", name: "Suède", currencyCode: "EUR", active: true },
  { code: "CH", name: "Suisse", currencyCode: "EUR", active: true },
  { code: "UA", name: "Ukraine", currencyCode: "EUR", active: true },
  { code: "GB", name: "Royaume-Uni", currencyCode: "GBP", active: true },
  { code: "VA", name: "Vatican", currencyCode: "EUR", active: true },

  // Amériques
  { code: "US", name: "États-Unis", currencyCode: "USD", active: true },
  { code: "CA", name: "Canada", currencyCode: "CAD", active: true },
  { code: "AG", name: "Antigua-et-Barbuda", currencyCode: "USD", active: true },
  { code: "AR", name: "Argentine", currencyCode: "USD", active: true },
  { code: "BS", name: "Bahamas", currencyCode: "USD", active: true },
  { code: "BB", name: "Barbade", currencyCode: "USD", active: true },
  { code: "BZ", name: "Belize", currencyCode: "USD", active: true },
  { code: "BO", name: "Bolivie", currencyCode: "USD", active: true },
  { code: "BR", name: "Brésil", currencyCode: "USD", active: true },
  { code: "CL", name: "Chili", currencyCode: "USD", active: true },
  { code: "CO", name: "Colombie", currencyCode: "USD", active: true },
  { code: "CR", name: "Costa Rica", currencyCode: "USD", active: true },
  { code: "CU", name: "Cuba", currencyCode: "USD", active: true },
  { code: "DM", name: "Dominique", currencyCode: "USD", active: true },
  { code: "DO", name: "République dominicaine", currencyCode: "USD", active: true },
  { code: "EC", name: "Équateur", currencyCode: "USD", active: true },
  { code: "SV", name: "Salvador", currencyCode: "USD", active: true },
  { code: "GD", name: "Grenade", currencyCode: "USD", active: true },
  { code: "GT", name: "Guatemala", currencyCode: "USD", active: true },
  { code: "GY", name: "Guyana", currencyCode: "USD", active: true },
  { code: "HT", name: "Haïti", currencyCode: "USD", active: true },
  { code: "HN", name: "Honduras", currencyCode: "USD", active: true },
  { code: "JM", name: "Jamaïque", currencyCode: "USD", active: true },
  { code: "MX", name: "Mexique", currencyCode: "USD", active: true },
  { code: "NI", name: "Nicaragua", currencyCode: "USD", active: true },
  { code: "PA", name: "Panama", currencyCode: "USD", active: true },
  { code: "PY", name: "Paraguay", currencyCode: "USD", active: true },
  { code: "PE", name: "Pérou", currencyCode: "USD", active: true },
  { code: "KN", name: "Saint-Christophe-et-Niévès", currencyCode: "USD", active: true },
  { code: "LC", name: "Sainte-Lucie", currencyCode: "USD", active: true },
  { code: "VC", name: "Saint-Vincent-et-les-Grenadines", currencyCode: "USD", active: true },
  { code: "SR", name: "Suriname", currencyCode: "USD", active: true },
  { code: "TT", name: "Trinité-et-Tobago", currencyCode: "USD", active: true },
  { code: "UY", name: "Uruguay", currencyCode: "USD", active: true },
  { code: "VE", name: "Venezuela", currencyCode: "USD", active: true },

  // Asie
  { code: "AF", name: "Afghanistan", currencyCode: "EUR", active: true },
  { code: "AM", name: "Arménie", currencyCode: "EUR", active: true },
  { code: "AZ", name: "Azerbaïdjan", currencyCode: "EUR", active: true },
  { code: "BH", name: "Bahreïn", currencyCode: "EUR", active: true },
  { code: "BD", name: "Bangladesh", currencyCode: "EUR", active: true },
  { code: "BT", name: "Bhoutan", currencyCode: "EUR", active: true },
  { code: "BN", name: "Brunei", currencyCode: "EUR", active: true },
  { code: "KH", name: "Cambodge", currencyCode: "EUR", active: true },
  { code: "CN", name: "Chine", currencyCode: "EUR", active: true },
  { code: "GE", name: "Géorgie", currencyCode: "EUR", active: true },
  { code: "IN", name: "Inde", currencyCode: "EUR", active: true },
  { code: "ID", name: "Indonésie", currencyCode: "EUR", active: true },
  { code: "IR", name: "Iran", currencyCode: "EUR", active: true },
  { code: "IQ", name: "Irak", currencyCode: "EUR", active: true },
  { code: "IL", name: "Israël", currencyCode: "EUR", active: true },
  { code: "JP", name: "Japon", currencyCode: "EUR", active: true },
  { code: "JO", name: "Jordanie", currencyCode: "EUR", active: true },
  { code: "KZ", name: "Kazakhstan", currencyCode: "EUR", active: true },
  { code: "KW", name: "Koweït", currencyCode: "EUR", active: true },
  { code: "KG", name: "Kirghizistan", currencyCode: "EUR", active: true },
  { code: "LA", name: "Laos", currencyCode: "EUR", active: true },
  { code: "LB", name: "Liban", currencyCode: "EUR", active: true },
  { code: "MY", name: "Malaisie", currencyCode: "EUR", active: true },
  { code: "MV", name: "Maldives", currencyCode: "EUR", active: true },
  { code: "MN", name: "Mongolie", currencyCode: "EUR", active: true },
  { code: "MM", name: "Myanmar", currencyCode: "EUR", active: true },
  { code: "NP", name: "Népal", currencyCode: "EUR", active: true },
  { code: "KP", name: "Corée du Nord", currencyCode: "EUR", active: true },
  { code: "OM", name: "Oman", currencyCode: "EUR", active: true },
  { code: "PK", name: "Pakistan", currencyCode: "EUR", active: true },
  { code: "PS", name: "Palestine", currencyCode: "EUR", active: true },
  { code: "PH", name: "Philippines", currencyCode: "EUR", active: true },
  { code: "QA", name: "Qatar", currencyCode: "EUR", active: true },
  { code: "SA", name: "Arabie saoudite", currencyCode: "EUR", active: true },
  { code: "SG", name: "Singapour", currencyCode: "EUR", active: true },
  { code: "KR", name: "Corée du Sud", currencyCode: "EUR", active: true },
  { code: "LK", name: "Sri Lanka", currencyCode: "EUR", active: true },
  { code: "SY", name: "Syrie", currencyCode: "EUR", active: true },
  { code: "TW", name: "Taïwan", currencyCode: "EUR", active: true },
  { code: "TJ", name: "Tadjikistan", currencyCode: "EUR", active: true },
  { code: "TH", name: "Thaïlande", currencyCode: "EUR", active: true },
  { code: "TL", name: "Timor oriental", currencyCode: "EUR", active: true },
  { code: "TR", name: "Turquie", currencyCode: "EUR", active: true },
  { code: "TM", name: "Turkménistan", currencyCode: "EUR", active: true },
  { code: "AE", name: "Émirats arabes unis", currencyCode: "EUR", active: true },
  { code: "UZ", name: "Ouzbékistan", currencyCode: "EUR", active: true },
  { code: "VN", name: "Vietnam", currencyCode: "EUR", active: true },
  { code: "YE", name: "Yémen", currencyCode: "EUR", active: true },

  // Océanie
  { code: "AU", name: "Australie", currencyCode: "EUR", active: true },
  { code: "FJ", name: "Fidji", currencyCode: "EUR", active: true },
  { code: "KI", name: "Kiribati", currencyCode: "EUR", active: true },
  { code: "MH", name: "Îles Marshall", currencyCode: "USD", active: true },
  { code: "FM", name: "Micronésie", currencyCode: "USD", active: true },
  { code: "NR", name: "Nauru", currencyCode: "EUR", active: true },
  { code: "NZ", name: "Nouvelle-Zélande", currencyCode: "EUR", active: true },
  { code: "PW", name: "Palaos", currencyCode: "USD", active: true },
  { code: "PG", name: "Papouasie-Nouvelle-Guinée", currencyCode: "EUR", active: true },
  { code: "WS", name: "Samoa", currencyCode: "EUR", active: true },
  { code: "SB", name: "Îles Salomon", currencyCode: "EUR", active: true },
  { code: "TO", name: "Tonga", currencyCode: "EUR", active: true },
  { code: "TV", name: "Tuvalu", currencyCode: "EUR", active: true },
  { code: "VU", name: "Vanuatu", currencyCode: "EUR", active: true },
] as const;
