-- Expands the country picker from the original 14-country Africa-only list
-- to every country in the world (user request), so a diaspora member's
-- country of residence isn't artificially restricted at signup. Mirrors
-- packages/config/src/countries.ts — keep both in sync manually, same as
-- every other catalog table.
--
-- currency_code here is a country's reference currency only — it does not
-- constrain what currency a project/funding/expense can use (currencies
-- table) and does not change Stripe billing behavior: an organization is
-- billed in XOF/XAF only when its country is in that CFA zone, every other
-- country bills in EUR by default regardless of which one it is (see
-- getBillingCurrency in packages/business/src/currency.ts). USD/GBP/CAD are
-- used below only where they're the country's actual real-world currency
-- and already exist in the currencies table; everywhere else defaults to EUR.
insert into public.countries (code, name, currency_code, active) values
  ('DZ', 'Algérie', 'EUR', true),
  ('AO', 'Angola', 'EUR', true),
  ('BW', 'Botswana', 'EUR', true),
  ('BI', 'Burundi', 'EUR', true),
  ('CF', 'République centrafricaine', 'XAF', true),
  ('KM', 'Comores', 'EUR', true),
  ('DJ', 'Djibouti', 'EUR', true),
  ('EG', 'Égypte', 'EUR', true),
  ('GQ', 'Guinée équatoriale', 'XAF', true),
  ('ER', 'Érythrée', 'EUR', true),
  ('SZ', 'Eswatini', 'EUR', true),
  ('ET', 'Éthiopie', 'EUR', true),
  ('GM', 'Gambie', 'EUR', true),
  ('GH', 'Ghana', 'EUR', true),
  ('GW', 'Guinée-Bissau', 'XOF', true),
  ('KE', 'Kenya', 'EUR', true),
  ('LS', 'Lesotho', 'EUR', true),
  ('LR', 'Liberia', 'EUR', true),
  ('LY', 'Libye', 'EUR', true),
  ('MG', 'Madagascar', 'EUR', true),
  ('MW', 'Malawi', 'EUR', true),
  ('MA', 'Maroc', 'EUR', true),
  ('MU', 'Maurice', 'EUR', true),
  ('MZ', 'Mozambique', 'EUR', true),
  ('NA', 'Namibie', 'EUR', true),
  ('NG', 'Nigeria', 'EUR', true),
  ('RW', 'Rwanda', 'EUR', true),
  ('ST', 'Sao Tomé-et-Principe', 'EUR', true),
  ('SC', 'Seychelles', 'EUR', true),
  ('SL', 'Sierra Leone', 'EUR', true),
  ('SO', 'Somalie', 'EUR', true),
  ('ZA', 'Afrique du Sud', 'EUR', true),
  ('SS', 'Soudan du Sud', 'EUR', true),
  ('SD', 'Soudan', 'EUR', true),
  ('TZ', 'Tanzanie', 'EUR', true),
  ('TD', 'Tchad', 'XAF', true),
  ('TN', 'Tunisie', 'EUR', true),
  ('UG', 'Ouganda', 'EUR', true),
  ('ZM', 'Zambie', 'EUR', true),
  ('ZW', 'Zimbabwe', 'EUR', true),
  ('AL', 'Albanie', 'EUR', true),
  ('AD', 'Andorre', 'EUR', true),
  ('AT', 'Autriche', 'EUR', true),
  ('BY', 'Biélorussie', 'EUR', true),
  ('BE', 'Belgique', 'EUR', true),
  ('BA', 'Bosnie-Herzégovine', 'EUR', true),
  ('BG', 'Bulgarie', 'EUR', true),
  ('HR', 'Croatie', 'EUR', true),
  ('CY', 'Chypre', 'EUR', true),
  ('CZ', 'République tchèque', 'EUR', true),
  ('DK', 'Danemark', 'EUR', true),
  ('EE', 'Estonie', 'EUR', true),
  ('FI', 'Finlande', 'EUR', true),
  ('FR', 'France', 'EUR', true),
  ('DE', 'Allemagne', 'EUR', true),
  ('GR', 'Grèce', 'EUR', true),
  ('HU', 'Hongrie', 'EUR', true),
  ('IS', 'Islande', 'EUR', true),
  ('IE', 'Irlande', 'EUR', true),
  ('IT', 'Italie', 'EUR', true),
  ('XK', 'Kosovo', 'EUR', true),
  ('LV', 'Lettonie', 'EUR', true),
  ('LI', 'Liechtenstein', 'EUR', true),
  ('LT', 'Lituanie', 'EUR', true),
  ('LU', 'Luxembourg', 'EUR', true),
  ('MT', 'Malte', 'EUR', true),
  ('MD', 'Moldavie', 'EUR', true),
  ('MC', 'Monaco', 'EUR', true),
  ('ME', 'Monténégro', 'EUR', true),
  ('NL', 'Pays-Bas', 'EUR', true),
  ('MK', 'Macédoine du Nord', 'EUR', true),
  ('NO', 'Norvège', 'EUR', true),
  ('PL', 'Pologne', 'EUR', true),
  ('PT', 'Portugal', 'EUR', true),
  ('RO', 'Roumanie', 'EUR', true),
  ('RU', 'Russie', 'EUR', true),
  ('SM', 'Saint-Marin', 'EUR', true),
  ('RS', 'Serbie', 'EUR', true),
  ('SK', 'Slovaquie', 'EUR', true),
  ('SI', 'Slovénie', 'EUR', true),
  ('ES', 'Espagne', 'EUR', true),
  ('SE', 'Suède', 'EUR', true),
  ('CH', 'Suisse', 'EUR', true),
  ('UA', 'Ukraine', 'EUR', true),
  ('GB', 'Royaume-Uni', 'GBP', true),
  ('VA', 'Vatican', 'EUR', true),
  ('US', 'États-Unis', 'USD', true),
  ('CA', 'Canada', 'CAD', true),
  ('AG', 'Antigua-et-Barbuda', 'USD', true),
  ('AR', 'Argentine', 'USD', true),
  ('BS', 'Bahamas', 'USD', true),
  ('BB', 'Barbade', 'USD', true),
  ('BZ', 'Belize', 'USD', true),
  ('BO', 'Bolivie', 'USD', true),
  ('BR', 'Brésil', 'USD', true),
  ('CL', 'Chili', 'USD', true),
  ('CO', 'Colombie', 'USD', true),
  ('CR', 'Costa Rica', 'USD', true),
  ('CU', 'Cuba', 'USD', true),
  ('DM', 'Dominique', 'USD', true),
  ('DO', 'République dominicaine', 'USD', true),
  ('EC', 'Équateur', 'USD', true),
  ('SV', 'Salvador', 'USD', true),
  ('GD', 'Grenade', 'USD', true),
  ('GT', 'Guatemala', 'USD', true),
  ('GY', 'Guyana', 'USD', true),
  ('HT', 'Haïti', 'USD', true),
  ('HN', 'Honduras', 'USD', true),
  ('JM', 'Jamaïque', 'USD', true),
  ('MX', 'Mexique', 'USD', true),
  ('NI', 'Nicaragua', 'USD', true),
  ('PA', 'Panama', 'USD', true),
  ('PY', 'Paraguay', 'USD', true),
  ('PE', 'Pérou', 'USD', true),
  ('KN', 'Saint-Christophe-et-Niévès', 'USD', true),
  ('LC', 'Sainte-Lucie', 'USD', true),
  ('VC', 'Saint-Vincent-et-les-Grenadines', 'USD', true),
  ('SR', 'Suriname', 'USD', true),
  ('TT', 'Trinité-et-Tobago', 'USD', true),
  ('UY', 'Uruguay', 'USD', true),
  ('VE', 'Venezuela', 'USD', true),
  ('AF', 'Afghanistan', 'EUR', true),
  ('AM', 'Arménie', 'EUR', true),
  ('AZ', 'Azerbaïdjan', 'EUR', true),
  ('BH', 'Bahreïn', 'EUR', true),
  ('BD', 'Bangladesh', 'EUR', true),
  ('BT', 'Bhoutan', 'EUR', true),
  ('BN', 'Brunei', 'EUR', true),
  ('KH', 'Cambodge', 'EUR', true),
  ('CN', 'Chine', 'EUR', true),
  ('GE', 'Géorgie', 'EUR', true),
  ('IN', 'Inde', 'EUR', true),
  ('ID', 'Indonésie', 'EUR', true),
  ('IR', 'Iran', 'EUR', true),
  ('IQ', 'Irak', 'EUR', true),
  ('IL', 'Israël', 'EUR', true),
  ('JP', 'Japon', 'EUR', true),
  ('JO', 'Jordanie', 'EUR', true),
  ('KZ', 'Kazakhstan', 'EUR', true),
  ('KW', 'Koweït', 'EUR', true),
  ('KG', 'Kirghizistan', 'EUR', true),
  ('LA', 'Laos', 'EUR', true),
  ('LB', 'Liban', 'EUR', true),
  ('MY', 'Malaisie', 'EUR', true),
  ('MV', 'Maldives', 'EUR', true),
  ('MN', 'Mongolie', 'EUR', true),
  ('MM', 'Myanmar', 'EUR', true),
  ('NP', 'Népal', 'EUR', true),
  ('KP', 'Corée du Nord', 'EUR', true),
  ('OM', 'Oman', 'EUR', true),
  ('PK', 'Pakistan', 'EUR', true),
  ('PS', 'Palestine', 'EUR', true),
  ('PH', 'Philippines', 'EUR', true),
  ('QA', 'Qatar', 'EUR', true),
  ('SA', 'Arabie saoudite', 'EUR', true),
  ('SG', 'Singapour', 'EUR', true),
  ('KR', 'Corée du Sud', 'EUR', true),
  ('LK', 'Sri Lanka', 'EUR', true),
  ('SY', 'Syrie', 'EUR', true),
  ('TW', 'Taïwan', 'EUR', true),
  ('TJ', 'Tadjikistan', 'EUR', true),
  ('TH', 'Thaïlande', 'EUR', true),
  ('TL', 'Timor oriental', 'EUR', true),
  ('TR', 'Turquie', 'EUR', true),
  ('TM', 'Turkménistan', 'EUR', true),
  ('AE', 'Émirats arabes unis', 'EUR', true),
  ('UZ', 'Ouzbékistan', 'EUR', true),
  ('VN', 'Vietnam', 'EUR', true),
  ('YE', 'Yémen', 'EUR', true),
  ('AU', 'Australie', 'EUR', true),
  ('FJ', 'Fidji', 'EUR', true),
  ('KI', 'Kiribati', 'EUR', true),
  ('MH', 'Îles Marshall', 'USD', true),
  ('FM', 'Micronésie', 'USD', true),
  ('NR', 'Nauru', 'EUR', true),
  ('NZ', 'Nouvelle-Zélande', 'EUR', true),
  ('PW', 'Palaos', 'USD', true),
  ('PG', 'Papouasie-Nouvelle-Guinée', 'EUR', true),
  ('WS', 'Samoa', 'EUR', true),
  ('SB', 'Îles Salomon', 'EUR', true),
  ('TO', 'Tonga', 'EUR', true),
  ('TV', 'Tuvalu', 'EUR', true),
  ('VU', 'Vanuatu', 'EUR', true)
on conflict (code) do nothing;

-- Cap-Vert was seeded as inactive originally; now that every country is
-- offered, there's no reason to keep it hidden.
update public.countries set active = true where code = 'CV';
